subdir('uridownloader')

subdir('adaptivedemux')
subdir('audio')
subdir('basecamerabinsrc')
subdir('basedrm')
subdir('codecparsers')
subdir('insertbin')
subdir('interfaces')
subdir('isoff')
subdir('mpegts')
subdir('multiapp')
subdir('opencv')
subdir('player')
subdir('video')
subdir('wayland')
subdir('webrtc')
