plugin_LTLIBRARIES = libgsth265combiner.la

libgsth265combiner_la_SOURCES = gsth265combiner.c
libgsth265combiner_la_CFLAGS = $(GST_PLUGINS_BASE_CFLAGS) $(GST_BASE_CFLAGS) $(GST_CFLAGS)
libgsth265combiner_la_LIBADD = $(GST_PLUGINS_BASE_LIBS) $(GST_BASE_LIBS) $(GST_LIBS)
libgsth265combiner_la_LDFLAGS = $(GST_PLUGIN_LDFLAGS)

noinst_HEADERS = gsth265combiner.h
